### ISSUE TITLE
`pdflatex` build failure

### ISSUE THREAD

**Issue by alcemirsantos** [christinaflach/pgcomp-ufba#3]
Prof. @christinaflach,

Estou tendo problemas com o build da proposta de tese via "pdflatex".

- Versão instalada: `pdfTeX 3.14159265-2.6-1.40.16 (TeX Live 2015)`;
- Meu arquivo .tex principal tem a seguinte configuração: `\documentclass[en, prop, scr, a4paper]{ufbathesis}`;
- Definição de diretórios de imagens `\graphicspath{{../images/}}`;
- Os pacotes do preâmbulo: 

   ```\usepackage[utf8]{inputenc}
\usepackage{hyphenat}
\usepackage[usenames, dvipsnames, table]{xcolor}
\usepackage{booktabs}
\usepackage{pifont}
\usepackage{multirow}
\usepackage{listings} 
\usepackage{colortbl}
\usepackage{xfrac}
\usepackage[FIGTOPCAP]{subfigure}
```

Os **novos** erros são os seguintes: 

> Missing \begin{document}. ...nst:Nn \c_sys_year_int { \tex_year:D } (followed by: ) (Occurance: /usr/local/texlive/2015/texmf-dist/tex/latex/l3kernel/expl3-code.tex)	main.tex	
>
> Missing $ inserted. ...nst:Nn \c_sys_year_int { \tex_year:D } (followed by: ) (Occurance: /usr/local/texlive/2015/texmf-dist/tex/latex/l3kernel/expl3-code.tex)	main.tex
>
> You can't use `\numexpr' in vertical mode. ...nst:Nn \c_sys_year_int { \tex_year:D } (followed by: ) (Occurance: /usr/local/texlive/2015/texmf-dist/tex/latex/l3kernel/expl3-code.tex)	main.tex	
>
> ==> Fatal error occurred, no output PDF file produced! (Occurance: /usr/local/texlive/2015/texmf-dist/tex/latex/l3kernel/expl3-code.tex)	main.tex	
>
> Missing = inserted for \ifnum. ...nst:Nn \c_sys_year_int { \tex_year:D } (followed by: ) (Occurance: /usr/local/texlive/2015/texmf-dist/tex/latex/l3kernel/expl3-code.tex)	main.tex	
>
> Missing number, treated as zero. ...nst:Nn \c_sys_year_int { \tex_year:D } (followed by: ) (Occurance: /usr/local/texlive/2015/texmf-dist/tex/latex/l3kernel/expl3-code.tex)	main.tex	
>
> TeX capacity exceeded, sorry [grouping levels=255]. ...nst:Nn \c_sys_year_int { \tex_year:D } (followed by: ) (Occurance: /usr/local/texlive/2015/texmf-dist/tex/latex/l3kernel/expl3-code.tex)	main.tex	
>
> Package hyperref Error: Wrong DVI mode driver option `dvipdfm', \ProcessKeyvalOptions{Hyp} (followed by: ) (Occurance: /usr/local/texlive/2015/texmf-dist/tex/latex/hyperref/hyperref.sty)	main.tex	

Antes do commit: 7529324f957a88c2f3ab8cb7f51633ff167378ce estava compilando normalmente, apenas os erros do `\begin{pquot@tion}...` aparecerem. Ainda assim o _.pdf_ era gerado.

**Velhos** erros (`\begin{pquot@tion}...`):

> \begin{pquot@tion} does not have matching end; at least one unbalanced begin-end	ufbathesis.cls		line 1124	
>
> \begin{pquot@tion} does not have matching end; at least one unbalanced begin-end	ufbathesis.cls		line 653
>

Edit:
------
- Se compilar sem nenhum conteúdo, somente com partes pré e pós textual, os erros continuam.

**Comment by alcemirsantos** [comment]
Passei a compilar o template para inspecionar o erro adicionando um a um dos pacotes do preâmbulo.
O erro aparece com o uso do **xfrac**.

` \usepackage{xfrac}`

**Comment by christinaflach** [comment]
Por favor, veja se o commit  36e1e9d  resolveu.

**Comment by christinaflach** [comment]
Não retirar 'classic' da declaração:

\documentclass[en, prop, classic, a4paper]{ufbathesis}

**Comment by alcemirsantos** [comment]
Sim, usando a opção `classic` gera o _.pdf_.  Mas os erros de `pquot@tion` no _.cls_ continuam.

> \begin{pquot@tion} does not have matching end; at least one unbalanced begin-end ufbathesis.cls line 1124
> \begin{pquot@tion} does not have matching end; at least one unbalanced begin-end ufbathesis.cls line 653

A opção `classic` não inclui os bookmarks no  _.pdf_, enquanto a `scr` deveria fazer isso, correto? Como utilizar as duas simultaneamente dá conflito, a versão com bookmarks, não está disponível, então?

**Comment by alcemirsantos** [comment]
Resolvi o problema dos bookmarks ao, na classe,  remover a opção `dvipdfm` na declaração do `hyperfef` em tempo do processamento da opção `scr` do `\documentclass[]{}`.
